# Generated by Django 4.2.8 on 2023-12-20 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calories', models.FloatField(blank=True, null=True)),
                ('protein_content', models.FloatField(blank=True, null=True)),
                ('carbohydrate_content', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sick', models.BooleanField(default=False)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True)),
                ('activity_level', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SickUserProfile',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Food.userprofile')),
                ('chronic_conditions', models.TextField(blank=True, null=True)),
                ('prescribed_medications', models.TextField(blank=True, null=True)),
            ],
            bases=('Food.userprofile',),
        ),
        migrations.CreateModel(
            name='MealFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='meal_images/')),
                ('grains_quantity', models.FloatField(blank=True, null=True)),
                ('proteins_quantity', models.FloatField(blank=True, null=True)),
                ('dairy_quantity', models.FloatField(blank=True, null=True)),
                ('fruits_quantity', models.FloatField(blank=True, null=True)),
                ('vegetables_quantity', models.FloatField(blank=True, null=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food.userprofile')),
            ],
        ),
    ]
